#!/bin/bash

testdir=./tests
outfile=out
commands=("./app.exe a $testdir/in_11 $testdir/in_12 $outfile"
"./app.exe m $testdir/in_21 $testdir/in_22 $outfile"
"./app.exe o $testdir/in_3 $outfile")
outputs=(out_1 out_2 out_3)





for i in ${!commands[*]}
do
    num=$(( $i + 1 ))

    echo -e "\nRunning test $num with command:\n${commands[$i]}"
    ${commands[$i]}

    diff ./$outfile $testdir/${outputs[$i]}
    if [ $? ] 
    then
        echo "Test $num successfully completed"
    else
        echo "Test $num is not passed"
        break
    fi
done


