#!/bin/bash

testdir=./tests
outfile=out
commands=("./app.exe a $testdir/in_11 $testdir/in_12 $outfile"
"./app.exe m $testdir/in_21 $testdir/in_22 $outfile"
"./app.exe o $testdir/in_3 $outfile")
outputs=(out_1 out_2 out_3)





for i in ${!commands[*]}
do
    num=$(( $i + 1 ))

    echo "Running test $num with command: ${commands[i]}"
    ${commands[i]}


    if [[ !$(diff ./$outfile $testdir/${outputs[i]}) ]] 
    then
        echo -e "Test $num successfully completed\n"
    else
        echo "Test $num is not passed"
        break
    fi
done


