#!/bin/bash


testdir=./tests


./app.exe a $testdir/in_11 $testdir/in_12 out
if [[ $(diff out $testdir/out_1) ]]
then
    echo "test 1 completed"
else
    echo "test 1 crashed"
fi


./app.exe m $testdir/in_21 $testdir/in_22 out
if [[ $(diff out $testdir/out_2) ]]
then
    echo "test 2 completed"
else
    echo "test 2 crashed"
fi


./app.exe m $testdir/in_3
if [[ $(diff out $testdir/out_3) ]]
then
    echo "test 3 completed"
else
    echo "test 3 crashed"
fi


